import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "NesxtJS Codevolution",
    template: "codevoltion|%s",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "lightblue", padding: "1rem" }}>
          Header
        </header>
        <nav>
          <Link href={"/about"}>About</Link>
          <Link href={"/products"}>Products</Link>
          <Link href={"/docs"}>Documentation</Link>
          <Link href={"/complex-dashboard"}>Dashboard</Link>
          <Link href={"/photo-feed"}>Photo-Feed</Link>
        </nav>
        {children}
        <footer style={{ backgroundColor: "ghostwhite", padding: "1rem" }}>
          Footer
        </footer>
      </body>
    </html>
  );
}
